/*
 FlexSearch v0.3.3
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/flexsearch
*/
'use strict';(function(g,r,c){let h;(h=c.define)&&h.amd?h([],function(){return r}):(h=c.modules)?h[g.toLowerCase()]=r:"object"===typeof exports?module.exports=r:c[g]=r})("FlexSearch",function(){function g(a){y(a)&&(a=G[a]);a||(a=t);this.id=a.id||M++;this.init(a);r(this,"index",function(){return this.b});r(this,"length",function(){return Object.keys(this.b).length})}function r(a,b,d){Object.defineProperty(a,b,{get:d})}function c(a){return new RegExp(a,"g")}function h(a,b){for(let d=0;d<b.length;d+=
2)a=a.replace(b[d],b[d+1]);return a}function x(a,b,d,f,e,c,k){if(b[d])return b[d];e=e?(9-(k||6))*c+(k||6)*e:c;b[d]=e;e>=k&&(a=a[e+.5>>0],a=a[d]||(a[d]=[]),a[a.length]=f);return e}function C(a,b){if(a){const d=Object.keys(a);for(let f=0,e=d.length;f<e;f++){const e=d[f],c=a[e];if(c)for(let d=0,f=c.length;d<f;d++)if(c[d]===b){1===f?delete a[e]:c.splice(d,1);break}else"object"===typeof c[d]&&C(c[d],b)}}}function D(a){let b="",d="";var f="";for(let e=0;e<a.length;e++){const c=a[e];if(c!==d)if(e&&"h"===
c){if(f="a"===f||"e"===f||"i"===f||"o"===f||"u"===f||"y"===f,("a"===d||"e"===d||"i"===d||"o"===d||"u"===d||"y"===d)&&f||" "===d)b+=c}else b+=c;f=e===a.length-1?"":a[e+1];d=c}return b}function N(a,b){a=a.length-b.length;return 0>a?1:a?-1:0}function O(a,b){a=a.length-b.length;return 0>a?-1:a?1:0}function P(a,b,d){let c=[],e=[];const u=a.length;if(1<u){a.sort(O);const f=q();let g=a[0],v=g.length,h=0;for(;h<v;)f[g[h++]]=1;let l,p=0,m=0;for(;++m<u;){let n=!1;const q=m===u-1;e=[];g=a[m];v=g.length;for(h=
0;h<v;)if(l=g[h++],f[l]){var k=f[l];if(k===m){if(q){if(c[p++]=l,b&&p===b)return c}else f[l]=m+1;n=!0}else d&&(k=e[k]||(e[k]=[]),k[k.length]=l)}if(!n&&!d)break}if(d&&(p=c.length,(m=e.length)&&(!b||p<b)))for(;m--;)if(l=e[m])for(let a=0,d=l.length;a<d;a++)if(c[p++]=l[a],b&&p===b)return c}else u&&(c=a[0],b&&c.length>b&&(c=c.slice(0,b)));return c}function y(a){return"string"===typeof a}function z(a){return"function"===typeof a}function A(a){return"undefined"===typeof a}function E(a){a.l||(a.l=H(function(){a.l=
0;{const b=a.async;let d;b&&(a.async=!1);if(a.c.length){const b=Date.now();let c;for(;(c=a.c.shift())||0===c;){d=a.f[c];switch(d[0]){case B.add:a.add(d[1],d[2]);break;case B.remove:a.remove(d[1])}delete a.f[c];if(100<Date.now()-b)break}a.c.length&&E(a)}b&&(a.async=b)}},1,"search-async-"+a.id))}function I(a){const b=Array(a);for(let d=0;d<a;d++)b[d]=q();return b}function q(){return Object.create(null)}const t={encode:"icase",a:"forward",m:!1,cache:!1,async:!1,o:!1,threshold:0,depth:0},G={memory:{encode:"extra",
a:"strict",threshold:7},speed:{encode:"icase",a:"strict",threshold:7,depth:2},match:{encode:"extra",a:"full"},score:{encode:"extra",a:"strict",threshold:5,depth:4},balance:{encode:"balance",a:"strict",threshold:6,depth:3},fastest:{encode:"icase",a:"strict",threshold:9,depth:1}},F=[];let M=0;const B={add:0,update:1,remove:2},J=c("\\W+"),K={},L={};(function(){const a=Object.getOwnPropertyNames({}.__proto__),b=q();for(let d=0;d<a.length;d++)b[a[d]]=1;return b})();g.create=function(a){return new g(a)};
g.registerMatcher=function(a){for(let b in a)a.hasOwnProperty(b)&&F.push(c(b),a[b]);return this};g.registerEncoder=function(a,b){w[a]=b.bind(w);return this};g.registerLanguage=function(a,b){K[a]=b.filter;L[a]=b.stemmer;return this};g.encode=function(a,b){return w[a](b)};g.prototype.init=function(a){this.j=[];a||(a=t);var b=a.profile,d=b?G[b]:{};this.a=a.tokenize||d.a||this.a||t.a;this.async=A(b=a.async)?this.async||t.async:b;this.threshold=A(b=a.threshold)?d.threshold||this.threshold||t.threshold:
b;this.depth=A(b=a.depth)?d.depth||this.depth||t.depth:b;this.h=(b=A(b=a.encode)?d.encode:b)&&w[b]&&w[b].bind(w)||(z(b)?b:this.h||!1);(b=a.matcher)&&this.addMatcher(b);if(b=a.filter){b=K[b]||b;d=this.h;var f=q();if(b)for(let a=0;a<b.length;a++){const c=d?d(b[a]):b[a];f[c]=String.fromCharCode(65E3-b.length+a)}this.filter=b=f}if(b=a.stemmer){var e;a=L[b]||b;b=this.h;d=[];if(a)for(e in a)a.hasOwnProperty(e)&&(f=b?b(e):e,d.push(c("(?=.{"+(f.length+3)+",})"+f+"$"),b?b(a[e]):a[e]));this.stemmer=e=d}this.i=
I(10);this.g=q();this.b=q();this.f=q();this.c=[];this.l=0;return this};g.prototype.encode=function(a){a&&F.length&&(a=h(a,F));a&&this.j.length&&(a=h(a,this.j));a&&this.h&&(a=this.h(a));a&&this.stemmer&&(a=h(a,this.stemmer));return a};g.prototype.addMatcher=function(a){const b=this.j;for(const d in a)a.hasOwnProperty(d)&&b.push(c(d),a[d]);return this};g.prototype.add=function(a,b,d){if(b&&y(b)&&(a||0===a))if(this.b[a]&&!d)this.update(a,b);else{if(this.async)return this.f[a]||(this.c[this.c.length]=
a),this.f[a]=[B.add,a,b],E(this),this;b=this.encode(b);if(!b.length)return this;d=this.a;b=z(d)?d(b):b.split(J);const f=q();f._ctx=q();const h=this.threshold,u=this.depth,l=this.i,p=b.length;for(let m=0;m<p;m++){var c=b[m];if(c){var e=c.length,g=(p-m)/p,k="";switch(d){case "reverse":case "both":for(var n=e-1;1<=n;n--)k=c[n]+k,x(l,f,k,a,(e-n)/e,g,h);k="";case "forward":for(n=0;n<e;n++)k+=c[n],x(l,f,k,a,1,g,h);break;case "full":for(n=0;n<e;n++){const b=(e-n)/e;for(let d=e;d>n;d--)k=c.substring(n,d),
x(l,f,k,a,b,g,h)}break;default:if(e=x(l,f,c,a,1,g,h),u&&1<p&&e>=h)for(e=f._ctx[c]||(f._ctx[c]=q()),c=this.g[c]||(this.g[c]=I(10)),g=m-u,k=m+u+1,0>g&&(g=0),k>p&&(k=p);g<k;g++)g!==m&&x(c,e,b[g],a,0,10-(g<m?m-g:g-m),h)}}}this.b[a]=1}return this};g.prototype.update=function(a,b){this.b[a]&&y(b)&&(this.remove(a),this.add(a,b,!0));return this};g.prototype.remove=function(a){if(this.b[a]){if(this.async)return this.f[a]||(this.c[this.c.length]=a),this.f[a]=[B.remove,a],E(this),this;for(let b=0;10>b;b++)C(this.i[b],
a);this.depth&&C(this.g,a);delete this.b[a]}return this};g.prototype.search=function(a,b,c,f){let d=a,g,k=[];"object"===typeof a&&((c=a.callback||b)&&(d.callback=null),b=a.limit,g=a.threshold,a=a.query);g||(g=this.threshold||0);z(b)?(c=b,b=1E3):b||0===b||(b=1E3);if(c){{let a=this;H(function(){c(a.search(d,b,null,!0));a=null},1,"search-"+this.id)}}else{if(!f&&this.async&&"function"!==typeof importScripts){let a=this;return new Promise(function(c){c(a.search(d,b,null,!0));a=null})}if(!a||!y(a))return k;
d=a;d=this.encode(d);if(!d.length)return k;a=this.a;a=z(a)?a(d):d.split(J);f=a.length;var h=!0,r=[],v=q();if(1<f)if(this.depth){var t=!0;var l=a[0];v[l]=1}else a.sort(N);var p;if(!t||(p=this.g)[l])for(let b=t?1:0;b<f;b++){const c=a[b];if(c){if(!v[c]){const a=[];let b=!1,d=0;if(l=t?p[l]:this.i){let f;for(let e=9;e>=g;e--)if(f=l[e][c])a[d++]=f,b=!0}if(b)r[r.length]=1<d?a.concat.apply([],a):a[0];else{h=!1;break}v[c]=1}l=c}}else h=!1;h&&(k=P(r,b,!1));return k}};g.prototype.clear=function(){this.destroy();
return this.init()};g.prototype.destroy=function(){this.filter=this.stemmer=this.i=this.g=this.b=this.f=this.c=null;return this};const w={icase:function(a){return a.toLowerCase()},simple:function(){const a=[c("[\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5]"),"a",c("[\u00e8\u00e9\u00ea\u00eb]"),"e",c("[\u00ec\u00ed\u00ee\u00ef]"),"i",c("[\u00f2\u00f3\u00f4\u00f5\u00f6\u0151]"),"o",c("[\u00f9\u00fa\u00fb\u00fc\u0171]"),"u",c("[\u00fd\u0177\u00ff]"),"y",c("\u00f1"),"n",c("\u00e7"),"c",c("\u00df"),"s",c(" & "),
" and ",c("[-/]")," ",c("[^a-z0-9 ]"),"",c("\\s+")," "];return function(b){b=h(b.toLowerCase(),a);return" "!==b?b:""}}(),advanced:function(){const a=[c("ae"),"a",c("ai"),"ei",c("ay"),"ei",c("ey"),"ei",c("oe"),"o",c("ue"),"u",c("ie"),"i",c("sz"),"s",c("zs"),"s",c("sh"),"s",c("ck"),"k",c("cc"),"k",c("dt"),"t",c("ph"),"f",c("pf"),"f",c("ou"),"o",c("uo"),"u"];return function(b,c){if(!b)return b;b=this.simple(b);2<b.length&&(b=h(b,a));c||1<b.length&&(b=D(b));return b}}(),extra:function(){const a=[c("p"),
"b",c("z"),"s",c("[cgq]"),"k",c("n"),"m",c("d"),"t",c("[vw]"),"f",c("[aeiouy]"),""];return function(b){if(!b)return b;b=this.advanced(b,!0);if(1<b.length){b=b.split(" ");for(let c=0;c<b.length;c++){const d=b[c];1<d.length&&(b[c]=d[0]+h(d.substring(1),a))}b=b.join(" ");b=D(b)}return b}}(),balance:function(){const a=[c("[-/]")," ",c("[^a-z0-9 ]"),"",c("\\s+")," "];return function(b){return D(h(b.toLowerCase(),a))}}()},H=function(){const a=q();return function(b,c,f){const d=a[f];d&&clearTimeout(d);return a[f]=
setTimeout(b,c)}}();return g}(!1),this);
