/*
 FlexSearch v0.3.1
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/flexsearch
*/
'use strict';function J(d){var c=0;return function(){return c<d.length?{done:!1,value:d[c++]}:{done:!0}}}function K(d){var c="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return c?c.call(d):{next:J(d)}}var S="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,T="function"==typeof Object.defineProperties?Object.defineProperty:function(d,c,a){d!=Array.prototype&&d!=Object.prototype&&(d[c]=a.value)};
function U(d,c){if(c){var a=S;d=d.split(".");for(var f=0;f<d.length-1;f++){var g=d[f];g in a||(a[g]={});a=a[g]}d=d[d.length-1];f=a[d];c=c(f);c!=f&&null!=c&&T(a,d,{configurable:!0,writable:!0,value:c})}}
U("Promise",function(d){function c(a){this.b=0;this.g=void 0;this.a=[];var p=this.c();try{a(p.resolve,p.reject)}catch(C){p.reject(C)}}function a(){this.a=null}function f(a){return a instanceof c?a:new c(function(p){p(a)})}if(d)return d;a.prototype.b=function(a){if(null==this.a){this.a=[];var p=this;this.c(function(){p.g()})}this.a.push(a)};var g=S.setTimeout;a.prototype.c=function(a){g(a,0)};a.prototype.g=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var c=0;c<a.length;++c){var d=
a[c];a[c]=null;try{d()}catch(z){this.f(z)}}}this.a=null};a.prototype.f=function(a){this.c(function(){throw a;})};c.prototype.c=function(){function a(a){return function(p){d||(d=!0,a.call(c,p))}}var c=this,d=!1;return{resolve:a(this.o),reject:a(this.f)}};c.prototype.o=function(a){if(a===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.s(a);else{a:switch(typeof a){case "object":var d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.m(a):this.h(a)}};
c.prototype.m=function(a){var c=void 0;try{c=a.then}catch(C){this.f(C);return}"function"==typeof c?this.u(c,a):this.h(a)};c.prototype.f=function(a){this.i(2,a)};c.prototype.h=function(a){this.i(1,a)};c.prototype.i=function(a,c){if(0!=this.b)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.b);this.b=a;this.g=c;this.j()};c.prototype.j=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)w.b(this.a[a]);this.a=null}};var w=new a;c.prototype.s=function(a){var c=this.c();
a.l(c.resolve,c.reject)};c.prototype.u=function(a,c){var d=this.c();try{a.call(c,d.resolve,d.reject)}catch(z){d.reject(z)}};c.prototype.then=function(a,d){function f(a,c){return"function"==typeof a?function(c){try{p(a(c))}catch(E){g(E)}}:c}var p,g,B=new c(function(a,c){p=a;g=c});this.l(f(a,p),f(d,g));return B};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.l=function(a,c){function d(){switch(f.b){case 1:a(f.g);break;case 2:c(f.g);break;default:throw Error("Unexpected state: "+
f.b);}}var f=this;null==this.a?w.b(d):this.a.push(d)};c.resolve=f;c.reject=function(a){return new c(function(c,d){d(a)})};c.race=function(a){return new c(function(c,d){for(var p=K(a),g=p.next();!g.done;g=p.next())f(g.value).l(c,d)})};c.all=function(a){var d=K(a),g=d.next();return g.done?f([]):new c(function(a,c){function p(c){return function(d){A[c]=d;v--;0==v&&a(A)}}var A=[],v=0;do A.push(void 0),v++,f(g.value).l(p(A.length-1),c),g=d.next();while(!g.done)})};return c});
(function(d,c,a){var f;(f=a.define)&&f.amd?f([],function(){return c}):(f=a.modules)?f[d.toLowerCase()]=c:"object"===typeof exports?module.exports=c:a[d]=c})("FlexSearch",function(){function d(b){F(b)&&(b=L[b]);b||(b=x);this.id=b.id||W++;this.init(b);c(this,"index",function(){return this.a});c(this,"length",function(){return Object.keys(this.a).length})}function c(b,e,a){Object.defineProperty(b,e,{get:a})}function a(b){return new RegExp(b,"g")}function f(b,e){for(var a=0;a<e.length;a+=2)b=b.replace(e[a],
e[a+1]);return b}function g(b,e,a,c,d,D,l){if(e[a])return e[a];d=d?(9-(l||6))*D+(l||6)*d:D;e[a]=d;d>=l&&(b=b[d+.5>>0],b=b[a]||(b[a]=[]),b[b.length]=c);return d}function w(b,e){if(b)for(var a=Object.keys(b),c=0,d=a.length;c<d;c++){var D=a[c],l=b[D];if(l)for(var f=0,h=l.length;f<h;f++)if(l[f]===e){1===h?delete b[D]:l.splice(f,1);break}else"object"===typeof l[f]&&w(l[f],e)}}function p(b){var e=[];if(!b)return e;for(var a=0,c=0,d=0,f="",l=b.length,g=0;g<l;g++){var h=b[g];"a"===h||"e"===h||"i"===h||"o"===
h||"u"===h||"y"===h?a++:c++;" "!==h&&(f+=h);if(" "===h||a>=(8<l?2:1)&&2<=c||2<=a&&c>=(8<l?2:1)||g===l-1)f&&(e[d]&&2<f.length&&d++,e[d]=e[d]?e[d]+f:f," "===h&&d++,f=""),c=a=0}return e}function B(b){for(var e="",a="",c="",d=0;d<b.length;d++){var f=b[d];if(f!==a)if(d&&"h"===f){if(c="a"===c||"e"===c||"i"===c||"o"===c||"u"===c||"y"===c,("a"===a||"e"===a||"i"===a||"o"===a||"u"===a||"y"===a)&&c||" "===a)e+=f}else e+=f;c=d===b.length-1?"":b[d+1];a=f}return e}function C(b,e){b=b.length-e.length;return 0>b?
1:b?-1:0}function z(b,e){b=b.length-e.length;return 0>b?-1:b?1:0}function V(b,e,a){var c=[],d=[],f=b.length;if(1<f){b.sort(z);for(var t={},g=b[0],h=g.length,q=0;q<h;)t[g[q++]]=1;for(var k,m=0,n=0;++n<f;){var r=!1,p=n===f-1;d=[];g=b[n];h=g.length;for(q=0;q<h;)if(k=g[q++],t[k]){var u=t[k];if(u===n){if(p){if(c[m++]=k,e&&m===e)return c}else t[k]=n+1;r=!0}else a&&(u=d[u]||(d[u]=[]),u[u.length]=k)}if(!r&&!a)break}if(a&&(m=c.length,(n=d.length)&&(!e||m<e)))for(;n--;)if(k=d[n])for(b=0,a=k.length;b<a;b++)if(c[m++]=
k[b],e&&m===e)return c}else f&&(c=b[0],e&&c.length>e&&(c=c.slice(0,e)));return c}function F(b){return"string"===typeof b}function A(b){return"function"===typeof b}function v(b){return"undefined"===typeof b}function H(b){b.j||(b.j=N(function(){b.j=0;var a=b.async;a&&(b.async=!1);if(b.b.length){for(var c=Date.now(),d;(d=b.b.shift())||0===d;){var f=b.c[d];switch(f[0]){case G.add:b.add(f[1],f[2]);break;case G.remove:b.remove(f[1])}delete b.c[d];if(100<Date.now()-c)break}b.b.length&&H(b)}a&&(b.async=a)},
1,"search-async-"+b.id))}function E(b){for(var a=Array(b),c=0;c<b;c++)a[c]={};return a}var x={encode:"icase",mode:"forward",v:!1,cache:!1,async:!1,w:!1,threshold:0,depth:0},L={memory:{encode:"extra",mode:"strict",threshold:7},speed:{encode:"icase",mode:"strict",threshold:7,depth:2},match:{encode:"extra",mode:"full"},score:{encode:"extra",mode:"strict",threshold:5,depth:4},balance:{encode:"balance",mode:"strict",threshold:6,depth:3},fastest:{encode:"icase",mode:"strict",threshold:9,depth:1}},I=[],
W=0,G={add:0,update:1,remove:2},O=a("[ -/]"),P={},Q={},R=function(){for(var b=Object.getOwnPropertyNames({}.__proto__),a={},c=0;c<b.length;c++)a[b[c]]=1;return a}();d.create=function(b){return new d(b)};d.registerMatcher=function(b){for(var e in b)b.hasOwnProperty(e)&&I.push(a(e),b[e]);return this};d.registerEncoder=function(b,a){y[b]=a.bind(y);return this};d.registerLanguage=function(b,a){P[b]=a.filter;Q[b]=a.stemmer;return this};d.encode=function(b,a){return R[b]?a:y[b](a)};d.prototype.init=function(b){this.i=
[];b||(b=x);var e=b.profile,c=e?L[e]:{};this.mode=b.mode||c.mode||this.mode||x.mode;this.async=v(e=b.async)?this.async||x.async:e;this.threshold=v(e=b.threshold)?c.threshold||this.threshold||x.threshold:e;this.depth=v(e=b.depth)?c.depth||this.depth||x.depth:e;this.g=(e=v(e=b.encode)?c.encode:e)&&y[e]&&y[e].bind(y)||(A(e)?e:this.g||!1);(e=b.matcher)&&this.addMatcher(e);if(e=b.filter){e=P[e]||e;c=this.g;var d={};if(e)for(var f=0;f<e.length;f++){var g=c?c(e[f]):e[f];d[g]=String.fromCharCode(65E3-e.length+
f)}this.filter=d}if(e=b.stemmer){b=Q[e]||e;e=this.g;c=[];if(b)for(var l in b)b.hasOwnProperty(l)&&(d=e?e(l):l,c.push(a("(?=.{"+(d.length+3)+",})"+d+"$"),e?e(b[l]):b[l]));this.stemmer=c}this.h=E(10);this.f={};this.a={};this.c={};this.b=[];this.j=0;return this};d.prototype.encode=function(b){b&&I.length&&(b=f(b,I));b&&this.i.length&&(b=f(b,this.i));b&&this.g&&(b=this.g(b));b&&this.stemmer&&(b=f(b,this.stemmer));return b};d.prototype.addMatcher=function(b){var e=this.i,c;for(c in b)b.hasOwnProperty(c)&&
e.push(a(c),b[c]);return this};d.prototype.add=function(b,a,c){if(a&&F(a)&&(b&&!R[b]||0===b))if(this.a[b]&&!c)this.update(b,a);else{if(this.async)return this.c[b]||(this.b[this.b.length]=b),this.c[b]=[G.add,b,a],H(this),this;a=this.encode(a);if(!a.length)return this;c=this.mode;a=A(c)?c(a):"ngram"===c?p(a):a.split(O);for(var e={_ctx:{}},d=this.threshold,f=this.depth,l=this.h,t=a.length,h=0;h<t;h++){var q=a[h];if(q){var k=q.length,m=(t-h)/t,n="";switch(c){case "reverse":case "both":for(var r=k-1;1<=
r;r--)n=q[r]+n,g(l,e,n,b,(k-r)/k,m,d);n="";case "forward":for(r=0;r<k;r++)n+=q[r],g(l,e,n,b,1,m,d);break;case "full":for(r=0;r<k;r++)for(var v=(k-r)/k,u=k;u>r;u--)n=q.substring(r,u),g(l,e,n,b,v,m,d);break;default:if(k=g(l,e,q,b,1,m,d),f&&1<t&&k>=d)for(k=e._ctx[q]||(e._ctx[q]={}),q=this.f[q]||(this.f[q]=E(10)),m=h-f,n=h+f+1,0>m&&(m=0),n>t&&(n=t);m<n;m++)m!==h&&g(q,k,a[m],b,0,10-(m<h?h-m:m-h),d)}}}this.a[b]=1}return this};d.prototype.update=function(a,c){this.a[a]&&F(c)&&(this.remove(a),this.add(a,
c,!0));return this};d.prototype.remove=function(a){if(this.a[a]){if(this.async)return this.c[a]||(this.b[this.b.length]=a),this.c[a]=[G.remove,a],H(this),this;for(var b=0;10>b;b++)w(this.h[b],a);this.depth&&w(this.f,a);delete this.a[a]}return this};d.prototype.search=function(a,c,d,f){var b=a,e=[];if("object"===typeof a){(d=a.callback||c)&&(b.callback=null);c=a.limit;var g=a.threshold;a=a.query}g||(g=this.threshold||0);A(c)?(d=c,c=1E3):c||0===c||(c=1E3);if(d){var t=this;N(function(){d(t.search(b,
c,null,!0));t=null},1,"search-"+this.id)}else{if(!f&&this.async){var h=this;return new Promise(function(a){a(h.search(b,c,null,!0));h=null})}if(!a||!F(a))return e;b=a;b=this.encode(b);if(!b.length)return e;a=this.mode;a=A(a)?a(b):"ngram"===a?p(b):b.split(O);f=a.length;var q=!0,k=[],m={};if(1<f)if(this.depth){var n=!0;var r=a[0];m[r]=1}else a.sort(C);var v;if(!n||(v=this.f)[r])for(var u=n?1:0;u<f;u++){var w=a[u];if(w&&!m[w]){var x=void 0;x=void 0;for(var M=!1,y=[],B=0,z=9;z>=g;z--)if(x=(n?v[r]:this.h)[z],
x=x[w])y[B++]=x,M=!0;if(M)k[k.length]=1<B?k.concat.apply([],y):y[0];else{q=!1;break}m[w]=1}r=w}else q=!1;q&&(e=V(k,c,!1));return e}};d.prototype.clear=function(){this.destroy();return this.init()};d.prototype.destroy=function(){this.filter=this.stemmer=this.h=this.f=this.a=this.c=this.b=null;return this};var y={icase:function(a){return a.toLowerCase()},simple:function(){var b=[a("[\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5]"),"a",a("[\u00e8\u00e9\u00ea\u00eb]"),"e",a("[\u00ec\u00ed\u00ee\u00ef]"),"i",a("[\u00f2\u00f3\u00f4\u00f5\u00f6\u0151]"),
"o",a("[\u00f9\u00fa\u00fb\u00fc\u0171]"),"u",a("[\u00fd\u0177\u00ff]"),"y",a("\u00f1"),"n",a("\u00e7"),"c",a("\u00df"),"s",a(" & ")," and ",a("[-/]")," ",a("[^a-z0-9 ]"),"",a("\\s\\s+")," "];return function(a){a=f(a.toLowerCase(),b);return" "!==a?a:""}}(),advanced:function(){var b=[a("ae"),"a",a("ai"),"ei",a("ay"),"ei",a("ey"),"ei",a("oe"),"o",a("ue"),"u",a("ie"),"i",a("sz"),"s",a("zs"),"s",a("sh"),"s",a("ck"),"k",a("cc"),"k",a("dt"),"t",a("ph"),"f",a("pf"),"f",a("ou"),"o",a("uo"),"u"];return function(a,
c){if(!a)return a;a=this.simple(a);2<a.length&&(a=f(a,b));c||1<a.length&&(a=B(a));return a}}(),extra:function(){var b=[a("p"),"b",a("z"),"s",a("[cgq]"),"k",a("n"),"m",a("d"),"t",a("[vw]"),"f",a("[aeiouy]"),""];return function(a){if(!a)return a;a=this.advanced(a,!0);if(1<a.length){a=a.split(" ");for(var c=0;c<a.length;c++){var d=a[c];1<d.length&&(a[c]=d[0]+f(d.substring(1),b))}a=a.join(" ");a=B(a)}return a}}(),balance:function(){var b=[a("[-/]")," ",a("[^a-z0-9 ]"),"",a("\\s\\s+")," "];return function(a){return B(f(a.toLowerCase(),
b))}}()},N=function(){var a={};return function(b,c,d){var e=a[d];e&&clearTimeout(e);return a[d]=setTimeout(b,c)}}();return d}(!1),this);
