/*
 FlexSearch v0.2.42
 Copyright 2018 Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/flexsearch
*/
'use strict';(function(d,t,m){var q;(q=m.define)&&q.amd?q([],function(){return t}):(q=m.modules)?q[d.toLowerCase()]=t:"undefined"!==typeof module?module.exports=t:m[d]=t})("FlexSearch",function(){function d(a){"string"===typeof a&&(a=A[a]);a||(a=y);this.id=a.id||D++;this.init(a);t(this,"index",function(){return this.a});t(this,"length",function(){return Object.keys(this.a).length})}function t(a,b,c){Object.defineProperty(a,b,{get:c})}function m(a){return new RegExp(a,"g")}function q(a,b,c){if("undefined"===
typeof c){for(c=0;c<b.length;c+=2)a=a.replace(b[c],b[c+1]);return a}return a.replace(b,c)}function x(a,b,c,l,e,h,g){if("undefined"===typeof b[c]){if(h)e=10-h;else{var f=e.indexOf(c);e=3/e.length*(e.length-f)+6/(f-e.lastIndexOf(" ",f))}f=e;b[c]=f;f>=g&&(a=a[f+.5|0],a=a[c]||(a[c]=[]),a[a.length]=l)}return f||b[c]}function z(a,b){if(a)for(var c=Object.keys(a),l=0,e=c.length;l<e;l++){var h=c[l],g=a[h];if(g)for(var f=0,p=g.length;f<p;f++)if(g[f]===b){1===p?delete a[h]:g.splice(f,1);break}else"object"===
typeof g[f]&&z(g[f],b)}}function B(a){var b=[];if(!a)return b;for(var c=0,l=0,e=0,h="",g=a.length,f=0;f<g;f++){var p=a[f];"a"===p||"e"===p||"i"===p||"o"===p||"u"===p||"y"===p?c++:l++;" "!==p&&(h+=p);if(" "===p||1<c&&1<l||2<c||2<l||f===g-1)h&&(b[e]&&2<h.length&&e++,b[e]=b[e]?b[e]+h:h," "===p&&e++,h=""),l=c=0}return b}function E(a,b){a=a.length-b.length;return 0>a?1:0<a?-1:0}function F(a,b){a=a.length-b.length;return 0>a?-1:0<a?1:0}function G(a,b){var c=[],l=a.length;if(1<l){a.sort(F);for(var e={},
h=a[0],g=h.length,f=0;f<g;)e[h[f++]]=1;for(var p,d=0,n=1;n<l;){var r=!1;h=a[n];g=h.length;for(f=0;f<g;)if(e[p=h[f++]]===n){if(n===l-1&&(c[d++]=p,b&&d===b)){r=!1;break}r=!0;e[p]=n+1}if(!r)break;n++}}else if(l&&(c=a[0],b&&c.length>b))return c.slice(0,b);return c}var y={encode:"icase",mode:"ngram",cache:!1,async:!1,m:!1,threshold:0,depth:0},A={memory:{encode:"extra",mode:"strict",threshold:7},speed:{encode:"icase",mode:"strict",threshold:7,depth:2},match:{encode:"extra",mode:"full"},score:{encode:"extra",
mode:"strict",threshold:5,depth:4},balance:{encode:"balance",mode:"ngram",threshold:6,depth:3},fastest:{encode:"icase",mode:"strict",threshold:9,depth:1}},v=[],D=0,C=m("[ -/]");d.new=function(a){return new this(a)};d.create=function(a){return d.new(a)};d.addMatcher=function(a){for(var b in a)a.hasOwnProperty(b)&&(v[v.length]=m(b),v[v.length]=a[b]);return this};d.register=function(a,b){w[a]=b;return this};d.encode=function(a,b){return w[a].call(w,b)};d.prototype.init=function(a){this.h=[];if(a){var b=
a.profile;b=b?A[b]:{};this.mode=a.mode||b.mode||this.mode||y.mode;this.threshold=a.threshold||b.threshold||this.threshold||y.threshold;this.depth=a.depth||b.depth||this.depth||y.depth;this.i=(b=a.encode||b.encode)&&w[b]||("function"===typeof b?b:this.i||!1);(b=a.matcher)&&this.addMatcher(b)}this.f=[{},{},{},{},{},{},{},{},{},{}];this.b={};this.a={};this.c="";this.g=!0;return this};d.prototype.encode=function(a){a&&v.length&&(a=q(a,v));a&&this.h.length&&(a=q(a,this.h));a&&this.i&&(a=this.i.call(w,
a));if(a&&this.j){a=a.split(" ");for(var b=0;b<a.length;b++){var c=this.j[a[b]];c&&(a[b]=c)}a=a.join(" ")}a&&this.l&&(a=q(a,this.l));return a};d.prototype.addMatcher=function(a){var b=this.h,c;for(c in a)a.hasOwnProperty(c)&&(b[b.length]=m(c),b[b.length]=a[c]);return this};d.prototype.add=function(a,b,c){if("string"===typeof b&&b&&(a||0===a))if(this.a[a]&&!c)this.update(a,b);else{b=this.encode(b);if(!b.length)return this;c=this.mode;for(var l="function"===typeof c?c(b):"ngram"===c?B(b):b.split(C),
e={_ctx:{}},h=this.threshold,g=this.depth,f=this.f,p=l.length,d=0;d<p;d++){var n=l[d];if(n){var r=n.length;switch(c){case "reverse":case "both":for(var u="",k=r-1;1<=k;k--)u=n[k]+u,x(f,e,u,a,b,0,h);case "forward":u="";for(k=0;k<r;k++)u+=n[k],x(f,e,u,a,b,0,h);break;case "full":for(k=0;k<r;k++)for(var m=r;m>k;m--)u=n.substring(k,m),x(f,e,u,a,b,0,h);break;default:if(k=x(f,e,n,a,b,g?1:0,h),g&&1<p&&k>=h)for(r=e._ctx[n]||(e._ctx[n]={}),n=this.b[n]||(this.b[n]=[{},{},{},{},{},{},{},{},{},{}]),k=d-g,m=d+
g+1,0>k&&(k=0),m>p&&(m=p);k<m;k++)k!==d&&x(n,r,l[k],a,b,k<d?d-k:k-d,h)}}}this.a[a]="1";this.g=!1}return this};d.prototype.update=function(a,b){this.a[a]&&b&&"string"===typeof b&&(this.remove(a),this.add(a,b,!0));return this};d.prototype.remove=function(a){if(this.a[a]){for(var b=0;10>b;b++)z(this.f[b],a);this.depth&&z(this.b,a);delete this.a[a];this.g=!1}return this};d.prototype.search=function(a,b,c){var l=[];if(a&&"object"===typeof a){c=a.callback||b;b=a.limit;var e=a.threshold;a=a.query}e=(e||
this.threshold||0)|0;"function"===typeof b?(c=b,b=1E3):b||(b=1E3);if(c){var h=this;H(function(){c(h.search(a,b));h=null},1,"search-"+this.id);return null}if(!a||"string"!==typeof a)return l;if(!this.g)this.g=!0;else if(this.c&&0===a.indexOf(this.c))return l;var g=this.encode(a);if(!g.length)return l;var f=this.mode;g="function"===typeof f?f(g):"ngram"===f?B(g):g.split(C);f=g.length;var d=!0,m=[],n={};if(1<f)if(this.depth){var r=!0,u=g[0];n[u]="1"}else g.sort(E);var k;if(!r||(k=this.b)[u])for(var q=
r?1:0;q<f;q++){var t=g[q];if(t&&!n[t]){for(var v,x=!1,w=[],y=0,z=9;z>=e;z--)if(v=(r?k[u]:this.f)[z][t])w[y++]=v,x=!0;if(x)m[m.length]=1<y?m.concat.apply([],w):w[0];else{d=!1;break}n[t]="1"}u=t}else d=!1;d&&(l=G(m,b));l.length?this.c="":this.c||(this.c=a);return l};d.prototype.reset=function(){this.destroy();return this.init()};d.prototype.destroy=function(){this.j=this.l=this.f=this.b=this.a=null;return this};var w={icase:function(a){return a.toLowerCase()},balance:function(){var a=[m("[-/]")," ",
m("[^a-z0-9 ]"),"",m("\\s\\s+")," ",m("[aeiouy]"),""];return function(b){b=q(b.toLowerCase(),a);for(var c="",d="",e="",h=0;h<b.length;h++){var g=b[h];if(g!==d)if(h&&"h"===g){if(e="a"===e||"e"===e||"i"===e||"o"===e||"u"===e||"y"===e,("a"===d||"e"===d||"i"===d||"o"===d||"u"===d||"y"===d)&&e||" "===d)c+=g}else c+=g;e=h===b.length-1?"":b[h+1];d=g}return c}}()},H=null;return d}(!1),this);
