/*
 FlexSearch v0.3.21
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/flexsearch
*/
'use strict';(function(f,t,u){let k;(k=u.define)&&k.amd?k([],function(){return t}):(k=u.modules)?k[f.toLowerCase()]=t:"object"===typeof exports?module.exports=t:u[f]=t})("FlexSearch",function(){function f(a){a||(a=w);this.id=a.id||G++;this.init(a);t(this,"index",function(){return this.a});t(this,"length",function(){return Object.keys(this.a).length})}function t(a,b,c){Object.defineProperty(a,b,{get:c})}function u(a,b){for(let c=0;c<b.length;c+=2)a=a.replace(b[c],b[c+1]);return a}function k(a,b,c,
e,d,h,g){if(b[c])return b[c];d=d?(9-(g||6))*h+(g||6)*d:h;b[c]=d;d>=g&&(a=a[d+.5>>0],a=a[c]||(a[c]=[]),a[a.length]=e);return d}function y(a,b){if(a){const c=Object.keys(a);for(let e=0,d=c.length;e<d;e++){const d=c[e],g=a[d];if(g)for(let c=0,e=g.length;c<e;c++)if(g[c]===b){1===e?delete a[d]:g.splice(c,1);break}else"object"===typeof g[c]&&y(g[c],b)}}}function H(a,b){a=a.length-b.length;return 0>a?1:a?-1:0}function I(a,b){a=a.length-b.length;return 0>a?-1:a?1:0}function x(a){return"function"===typeof a}
function z(a){return"undefined"===typeof a}function B(a){const b=Array(a);for(let c=0;c<a;c++)b[c]={};return b}const w={encode:"icase",b:"forward",i:!1,cache:!1,async:!1,j:!1,threshold:0,depth:0},A=[];let G=0;const C=/[\s/-]/g,D={},E={},F=function(){const a=Object.getOwnPropertyNames({}.__proto__),b={};for(let c=0;c<a.length;c++)b[a[c]]=1;return b}();f.create=function(a){return new f(a)};f.registerMatcher=function(a){for(let b in a)a.hasOwnProperty(b)&&A.push(new RegExp(b,"g"),a[b]);return this};
f.registerEncoder=function(a,b){v[a]=b.bind(v);return this};f.registerLanguage=function(a,b){D[a]=b.filter;E[a]=b.stemmer;return this};f.encode=function(a,b){return F[a]?b:v[a](b)};f.prototype.init=function(a){this.h=[];a||(a=w);var b=a.profile,c={};this.b=a.tokenize||c.b||this.b||w.b;this.threshold=z(b=a.threshold)?c.threshold||this.threshold||w.threshold:b;this.depth=z(b=a.depth)?c.depth||this.depth||w.depth:b;this.f=(b=z(b=a.encode)?c.encode:b)&&v[b]&&v[b].bind(v)||(x(b)?b:this.f||!1);(b=a.matcher)&&
this.addMatcher(b);if(b=a.filter){b=D[b]||b;c=this.f;var e={};if(b)for(let a=0;a<b.length;a++){const d=c?c(b[a]):b[a];e[d]=String.fromCharCode(65E3-b.length+a)}this.filter=b=e}if(b=a.stemmer){var d;a=E[b]||b;b=this.f;c=[];if(a)for(d in a)a.hasOwnProperty(d)&&(e=b?b(d):d,c.push(new RegExp("(?=.{"+(e.length+3)+",})"+e+"$","g"),b?b(a[d]):a[d]));this.stemmer=d=c}this.g=B(10);this.c={};this.a={};return this};f.prototype.encode=function(a){a&&A.length&&(a=u(a,A));a&&this.h.length&&(a=u(a,this.h));a&&this.f&&
(a=this.f(a));a&&this.stemmer&&(a=u(a,this.stemmer));return a};f.prototype.addMatcher=function(a){const b=this.h;for(const c in a)a.hasOwnProperty(c)&&b.push(new RegExp(c,"g"),a[c]);return this};f.prototype.add=function(a,b,c){if(b&&"string"===typeof b&&(a&&!F[a]||0===a))if(this.a[a]&&!c)this.update(a,b);else{b=this.encode(b);if(!b.length)return this;c=this.b;b=x(c)?c(b):b.split(C);const f={_ctx:{}},l=this.threshold,r=this.depth,q=this.g,n=b.length;for(let p=0;p<n;p++){var e=b[p];if(e){var d=e.length,
h=(n-p)/n,g="";switch(c){case "reverse":case "both":for(var m=d-1;1<=m;m--)g=e[m]+g,k(q,f,g,a,(d-m)/d,h,l);g="";case "forward":for(m=0;m<d;m++)g+=e[m],k(q,f,g,a,1,h,l);break;case "full":for(m=0;m<d;m++){const b=(d-m)/d;for(let c=d;c>m;c--)g=e.substring(m,c),k(q,f,g,a,b,h,l)}break;default:if(d=k(q,f,e,a,1,h,l),r&&1<n&&d>=l)for(d=f._ctx[e]||(f._ctx[e]={}),e=this.c[e]||(this.c[e]=B(10)),h=p-r,g=p+r+1,0>h&&(h=0),g>n&&(g=n);h<g;h++)h!==p&&k(e,d,b[h],a,0,10-(h<p?p-h:h-p),l)}}}this.a[a]=1}return this};f.prototype.update=
function(a,b){this.a[a]&&"string"===typeof b&&(this.remove(a),this.add(a,b,!0));return this};f.prototype.remove=function(a){if(this.a[a]){for(let b=0;10>b;b++)y(this.g[b],a);this.depth&&y(this.c,a);delete this.a[a]}return this};f.prototype.search=function(a,b,c){var e=a,d=[];if("object"===typeof a){b=a.limit;var h=a.threshold;a=a.query}h||(h=this.threshold||0);x(b)?(c=b,b=1E3):b||0===b||(b=1E3);if(c)c(this.search(e,b,null,!0));else{if(!a||"string"!==typeof a)return d;e=this.encode(a);if(!e.length)return d;
a=this.b;a=x(a)?a(e):e.split(C);c=a.length;var g=!0;e=[];var f={};if(1<c)if(this.depth){var k=!0;var l=a[0];f[l]=1}else a.sort(H);var r;if(!k||(r=this.c)[l])for(var q=k?1:0;q<c;q++){var n=a[q];if(n&&!f[n]){let a=!1;const b=[];let c=0;for(let d=9;d>=h;d--){var p=(k?r[l]:this.g)[d];if(p=p[n])b[c++]=p,a=!0}if(a)e[e.length]=1<c?e.concat.apply([],b):b[0];else{g=!1;break}f[n]=1}l=n}else g=!1;if(g)a:{h=[];d=e.length;if(1<d){e.sort(I);l={};k=e[0];r=k.length;for(a=0;a<r;)l[k[a++]]=1;for(f=g=0;++f<d;){q=!1;
n=f===d-1;k=e[f];r=k.length;for(a=0;a<r;)if(c=k[a++],l[c]&&l[c]===f){if(n){if(h[g++]=c,b&&g===b){d=h;break a}}else l[c]=f+1;q=!0}if(!q)break}}else d&&(h=e[0],b&&h.length>b&&(h=h.slice(0,b)));d=h}return d}};f.prototype.clear=function(){this.destroy();return this.init()};f.prototype.destroy=function(){this.filter=this.stemmer=this.g=this.c=this.a=null;return this};const v={icase:function(a){return a.toLowerCase()}};return f}(!1),this);
