/*
 FlexSearch v0.3.5
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/flexsearch
*/
'use strict';(function(f,r,d){let h;(h=d.define)&&h.amd?h([],function(){return r}):(h=d.modules)?h[f.toLowerCase()]=r:"object"===typeof exports?module.exports=r:d[f]=r})("FlexSearch",function(){function f(a){z(a)&&(a=F[a]);a||(a=v);this.id=a.id||L++;this.init(a);r(this,"index",function(){return this.b});r(this,"length",function(){return Object.keys(this.b).length})}function r(a,b,c){Object.defineProperty(a,b,{get:c})}function d(a){return new RegExp(a,"g")}function h(a,b){for(let c=0;c<b.length;c+=
2)a=a.replace(b[c],b[c+1]);return a}function y(a,b,c,g,e,d,m){if(b[c])return b[c];e=e?(9-(m||6))*d+(m||6)*e:d;b[c]=e;e>=m&&(a=a[9-(e+.5>>0)],a=a[c]||(a[c]=[]),a[a.length]=g);return e}function C(a,b){if(a){const c=Object.keys(a);for(let g=0,d=c.length;g<d;g++){const d=c[g],e=a[d];if(e)for(let c=0,g=e.length;c<g;c++)if(e[c]===b){1===g?delete a[d]:e.splice(c,1);break}else"object"===typeof e[c]&&C(e[c],b)}}}function D(a){let b="",c="";var d="";for(let e=0;e<a.length;e++){const g=a[e];if(g!==c)if(e&&"h"===
g){if(d="a"===d||"e"===d||"i"===d||"o"===d||"u"===d||"y"===d,("a"===c||"e"===c||"i"===c||"o"===c||"u"===c||"y"===c)&&d||" "===c)b+=g}else b+=g;d=e===a.length-1?"":a[e+1];c=g}return b}function M(a,b){a=a.length-b.length;return 0>a?1:a?-1:0}function N(a,b){a=a.length-b.length;return 0>a?-1:a?1:0}function O(a,b,c){let d=[],e;const u=a.length;if(1<u){a.sort(N);const g=t();let l=a[0],n=l.length,k=0;for(;k<n;)g["@"+l[k++]]=1;let f,p=0,q=0;for(;++q<u;){let G=!1;const h=q===u-1;e=[];l=a[q];n=l.length;for(k=
0;k<n;){f=l[k++];var m="@"+f;if(g[m]){const a=g[m];if(a===q){if(h){if(d[p++]=f,b&&p===b)return d}else g[m]=q+1;G=!0}else c&&(m=e[a]||(e[a]=[]),m[m.length]=f)}}if(!G&&!c)break}if(c&&(p=d.length,(q=e.length)&&(!b||p<b)))for(;q--;)if(f=e[q])for(let a=0,c=f.length;a<c;a++)if(d[p++]=f[a],b&&p===b)return d}else u&&(d=a[0],b&&d.length>b&&(d=d.slice(0,b)));return d}function z(a){return"string"===typeof a}function A(a){return"function"===typeof a}function B(a){return"undefined"===typeof a}function H(a){const b=
Array(a);for(let c=0;c<a;c++)b[c]=t();return b}function t(){return Object.create(null)}const v={encode:"icase",a:"forward",i:!1,cache:!1,async:!1,j:!1,threshold:0,depth:0},F={memory:{encode:"extra",a:"strict",threshold:7},speed:{encode:"icase",a:"strict",threshold:7,depth:2},match:{encode:"extra",a:"full"},score:{encode:"extra",a:"strict",threshold:5,depth:4},balance:{encode:"balance",a:"strict",threshold:6,depth:3},fastest:{encode:"icase",a:"strict",threshold:9,depth:1}},E=[];let L=0;const I=d("\\W+"),
J={},K={};(function(){const a=Object.getOwnPropertyNames({}.__proto__),b=t();for(let c=0;c<a.length;c++)b[a[c]]=1;return b})();f.create=function(a){return new f(a)};f.registerMatcher=function(a){for(let b in a)a.hasOwnProperty(b)&&E.push(d(b),a[b]);return this};f.registerEncoder=function(a,b){x[a]=b.bind(x);return this};f.registerLanguage=function(a,b){J[a]=b.filter;K[a]=b.stemmer;return this};f.encode=function(a,b){return x[a](b)};f.prototype.init=function(a){this.h=[];a||(a=v);var b=a.profile,c=
b?F[b]:{};this.a=a.tokenize||c.a||this.a||v.a;this.async="undefined"===typeof Promise||B(b=a.async)?this.async||v.async:b;this.threshold=B(b=a.threshold)?c.threshold||this.threshold||v.threshold:b;this.depth=B(b=a.depth)?c.depth||this.depth||v.depth:b;this.f=(b=B(b=a.encode)?c.encode:b)&&x[b]&&x[b].bind(x)||(A(b)?b:this.f||!1);(b=a.matcher)&&this.addMatcher(b);if(b=a.filter){b=J[b]||b;c=this.f;var g=t();if(b)for(let a=0;a<b.length;a++){const d=c?c(b[a]):b[a];g[d]=String.fromCharCode(65E3-b.length+
a)}this.filter=b=g}if(b=a.stemmer){var e;a=K[b]||b;b=this.f;c=[];if(a)for(e in a)a.hasOwnProperty(e)&&(g=b?b(e):e,c.push(d("(?=.{"+(g.length+3)+",})"+g+"$"),b?b(a[e]):a[e]));this.stemmer=e=c}this.g=H(10-(this.threshold||0));this.c=t();this.b=t();return this};f.prototype.encode=function(a){a&&E.length&&(a=h(a,E));a&&this.h.length&&(a=h(a,this.h));a&&this.f&&(a=this.f(a));a&&this.stemmer&&(a=h(a,this.stemmer));return a};f.prototype.addMatcher=function(a){const b=this.h;for(const c in a)a.hasOwnProperty(c)&&
b.push(d(c),a[c]);return this};f.prototype.add=function(a,b,c,d,e){if(b&&z(b)&&(a||0===a)){var g="@"+a;if(this.b[g]&&!d)return this.update(a,b);if(!e){if(this.async&&"function"!==typeof importScripts){let e=this;g=new Promise(function(c){setTimeout(function(){e.add(a,b,null,d,!0);e=null;c()})});if(c)g.then(c);else return g;return this}if(c)return this.add(a,b,null,d,!0),c(),this}b=this.encode(b);if(!b.length)return this;c=this.a;e=A(c)?c(b):b.split(I);const h=t();h._ctx=t();const p=this.threshold,
q=this.depth,u=this.g,w=e.length;for(let b=0;b<w;b++){var m=e[b];if(m){var f=m.length,l=(w-b)/w,n="";switch(c){case "reverse":case "both":for(var k=f-1;1<=k;k--)n=m[k]+n,y(u,h,n,a,(f-k)/f,l,p);n="";case "forward":for(k=0;k<f;k++)n+=m[k],y(u,h,n,a,1,l,p);break;case "full":for(k=0;k<f;k++){const b=(f-k)/f;for(let c=f;c>k;c--)n=m.substring(k,c),y(u,h,n,a,b,l,p)}break;default:if(f=y(u,h,m,a,1,l,p),q&&1<w&&f>=p)for(f=h._ctx[m]||(h._ctx[m]=t()),m=this.c[m]||(this.c[m]=H(10-(p||0))),l=b-q,n=b+q+1,0>l&&(l=
0),n>w&&(n=w);l<n;l++)l!==b&&y(m,f,e[l],a,0,10-(l<b?b-l:l-b),p)}}}this.b[g]=1}return this};f.prototype.update=function(a,b,c){this.b["@"+a]&&z(b)&&(this.remove(a),this.add(a,b,c,!0));return this};f.prototype.remove=function(a,b,c){var d="@"+a;if(this.b[d]){if(!c){if(this.async&&"function"!==typeof importScripts){let c=this;d=new Promise(function(b){setTimeout(function(){c.remove(a,null,!0);c=null;b()})});if(b)d.then(b);else return d;return this}if(b)return this.remove(a,null,!0),b(),this}for(b=0;b<
10-(this.threshold||0);b++)C(this.g[b],a);this.depth&&C(this.c,a);delete this.b[d]}return this};f.prototype.search=function(a,b,c,d){let e=a;let f=[];if("object"===typeof a){(c=a.callback||b)&&(e.callback=null);b=a.limit;var g=a.threshold;a=a.query}g||(g=this.threshold||0);A(b)?(c=b,b=1E3):b||0===b||(b=1E3);if(!d){if(this.async&&"function"!==typeof importScripts){let a=this;g=new Promise(function(c){setTimeout(function(){c(a.search(e,b,null,!0));a=null})});if(c)g.then(c);else return g;return this}if(c)return c(this.search(e,
b,null,!0)),this}if(!a||!z(a))return f;e=a;e=this.encode(e);if(!e.length)return f;c=this.a;c=A(c)?c(e):e.split(I);a=c.length;d=!0;const h=[],l=t();let n;if(1<a)if(this.depth){n=!0;var k=c[0];l[k]=1}else c.sort(M);let r;if(!n||(r=this.c)[k])for(let b=n?1:0;b<a;b++){const a=c[b];if(a){if(!l[a]){const b=[];let c=!1,e=0;if(k=n?r[k]:this.g){let d;for(let f=0;f<10-g;f++)if(d=k[f][a])b[e++]=d,c=!0}if(c)h[h.length]=1<e?b.concat.apply([],b):b[0];else{d=!1;break}l[a]=1}k=a}}else d=!1;d&&(f=O(h,b,!1));return f};
f.prototype.clear=function(){return this.destroy().init()};f.prototype.destroy=function(){this.g=this.c=this.b=null;return this};const x={icase:function(a){return a.toLowerCase()},simple:function(){const a=[d("[\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5]"),"a",d("[\u00e8\u00e9\u00ea\u00eb]"),"e",d("[\u00ec\u00ed\u00ee\u00ef]"),"i",d("[\u00f2\u00f3\u00f4\u00f5\u00f6\u0151]"),"o",d("[\u00f9\u00fa\u00fb\u00fc\u0171]"),"u",d("[\u00fd\u0177\u00ff]"),"y",d("\u00f1"),"n",d("\u00e7"),"c",d("\u00df"),"s",d(" & "),
" and ",d("[-/]")," ",d("[^a-z0-9 ]"),"",d("\\s+")," "];return function(b){b=h(b.toLowerCase(),a);return" "!==b?b:""}}(),advanced:function(){const a=[d("ae"),"a",d("ai"),"ei",d("ay"),"ei",d("ey"),"ei",d("oe"),"o",d("ue"),"u",d("ie"),"i",d("sz"),"s",d("zs"),"s",d("sh"),"s",d("ck"),"k",d("cc"),"k",d("dt"),"t",d("ph"),"f",d("pf"),"f",d("ou"),"o",d("uo"),"u"];return function(b,c){if(!b)return b;b=this.simple(b);2<b.length&&(b=h(b,a));c||1<b.length&&(b=D(b));return b}}(),extra:function(){const a=[d("p"),
"b",d("z"),"s",d("[cgq]"),"k",d("n"),"m",d("d"),"t",d("[vw]"),"f",d("[aeiouy]"),""];return function(b){if(!b)return b;b=this.advanced(b,!0);if(1<b.length){b=b.split(" ");for(let c=0;c<b.length;c++){const d=b[c];1<d.length&&(b[c]=d[0]+h(d.substring(1),a))}b=b.join(" ");b=D(b)}return b}}(),balance:function(){const a=[d("[-/]")," ",d("[^a-z0-9 ]"),"",d("\\s+")," "];return function(b){return D(h(b.toLowerCase(),a))}}()};return f}(!1),this);
