/*
 FlexSearch v0.3.3
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/flexsearch
*/
'use strict';(function(e,u,v){let k;(k=v.define)&&k.amd?k([],function(){return u}):(k=v.modules)?k[e.toLowerCase()]=u:"object"===typeof exports?module.exports=u:v[e]=u})("FlexSearch",function(){function e(a){a||(a=x);this.id=a.id||G++;this.init(a);u(this,"index",function(){return this.a});u(this,"length",function(){return Object.keys(this.a).length})}function u(a,b,c){Object.defineProperty(a,b,{get:c})}function v(a,b){for(let c=0;c<b.length;c+=2)a=a.replace(b[c],b[c+1]);return a}function k(a,b,c,
f,d,m,g){if(b[c])return b[c];d=d?(9-(g||6))*m+(g||6)*d:m;b[c]=d;d>=g&&(a=a[9-(d+.5>>0)],a=a[c]||(a[c]=[]),a[a.length]=f);return d}function z(a,b){if(a){const c=Object.keys(a);for(let f=0,d=c.length;f<d;f++){const d=c[f],g=a[d];if(g)for(let c=0,f=g.length;c<f;c++)if(g[c]===b){1===f?delete a[d]:g.splice(c,1);break}else"object"===typeof g[c]&&z(g[c],b)}}}function H(a,b){a=a.length-b.length;return 0>a?1:a?-1:0}function I(a,b){a=a.length-b.length;return 0>a?-1:a?1:0}function y(a){return"function"===typeof a}
function A(a){return"undefined"===typeof a}function C(a){const b=Array(a);for(let c=0;c<a;c++)b[c]=r();return b}function r(){return Object.create(null)}const x={encode:"icase",f:"forward",i:!1,cache:!1,async:!1,j:!1,threshold:0,depth:0},B=[];let G=0;const D=/\W+/g,E={},F={};(function(){const a=Object.getOwnPropertyNames({}.__proto__),b=r();for(let c=0;c<a.length;c++)b[a[c]]=1;return b})();e.create=function(a){return new e(a)};e.registerMatcher=function(a){for(let b in a)a.hasOwnProperty(b)&&B.push(new RegExp(b,
"g"),a[b]);return this};e.registerEncoder=function(a,b){w[a]=b.bind(w);return this};e.registerLanguage=function(a,b){E[a]=b.filter;F[a]=b.stemmer;return this};e.encode=function(a,b){return w[a](b)};e.prototype.init=function(a){this.h=[];a||(a=x);var b=a.profile,c={};this.f=a.tokenize||c.f||this.f||x.f;this.threshold=A(b=a.threshold)?c.threshold||this.threshold||x.threshold:b;this.depth=A(b=a.depth)?c.depth||this.depth||x.depth:b;this.g=(b=A(b=a.encode)?c.encode:b)&&w[b]&&w[b].bind(w)||(y(b)?b:this.g||
!1);(b=a.matcher)&&this.addMatcher(b);if(b=a.filter){b=E[b]||b;c=this.g;var f=r();if(b)for(let a=0;a<b.length;a++){const d=c?c(b[a]):b[a];f[d]=String.fromCharCode(65E3-b.length+a)}this.filter=b=f}if(b=a.stemmer){var d;a=F[b]||b;b=this.g;c=[];if(a)for(d in a)a.hasOwnProperty(d)&&(f=b?b(d):d,c.push(new RegExp("(?=.{"+(f.length+3)+",})"+f+"$","g"),b?b(a[d]):a[d]));this.stemmer=d=c}this.c=C(10-(this.threshold||0));this.b=r();this.a=r();r();return this};e.prototype.encode=function(a){a&&B.length&&(a=v(a,
B));a&&this.h.length&&(a=v(a,this.h));a&&this.g&&(a=this.g(a));a&&this.stemmer&&(a=v(a,this.stemmer));return a};e.prototype.addMatcher=function(a){const b=this.h;for(const c in a)a.hasOwnProperty(c)&&b.push(new RegExp(c,"g"),a[c]);return this};e.prototype.add=function(a,b,c){if(b&&"string"===typeof b&&(a||0===a)){const e="@"+a;if(this.a[e]&&!c)this.update(a,b);else{b=this.encode(b);if(!b.length)return this;c=this.f;b=y(c)?c(b):b.split(D);const l=r();l._ctx=r();const n=this.threshold,t=this.depth,
q=this.c,p=b.length;for(let e=0;e<p;e++){var f=b[e];if(f){var d=f.length,m=(p-e)/p,g="";switch(c){case "reverse":case "both":for(var h=d-1;1<=h;h--)g=f[h]+g,k(q,l,g,a,(d-h)/d,m,n);g="";case "forward":for(h=0;h<d;h++)g+=f[h],k(q,l,g,a,1,m,n);break;case "full":for(h=0;h<d;h++){const b=(d-h)/d;for(let c=d;c>h;c--)g=f.substring(h,c),k(q,l,g,a,b,m,n)}break;default:if(d=k(q,l,f,a,1,m,n),t&&1<p&&d>=n)for(d=l._ctx[f]||(l._ctx[f]=r()),f=this.b[f]||(this.b[f]=C(10-(n||0))),m=e-t,g=e+t+1,0>m&&(m=0),g>p&&(g=
p);m<g;m++)m!==e&&k(f,d,b[m],a,0,10-(m<e?e-m:m-e),n)}}}this.a[e]=1}}return this};e.prototype.update=function(a,b){this.a["@"+a]&&"string"===typeof b&&(this.remove(a),this.add(a,b,!0));return this};e.prototype.remove=function(a){const b="@"+a;if(this.a[b]){for(let b=0;b<10-(this.threshold||0);b++)z(this.c[b],a);this.depth&&z(this.b,a);delete this.a[b]}return this};e.prototype.search=function(a,b,c){var f=a,d=[];if("object"===typeof a){b=a.limit;var e=a.threshold;a=a.query}e||(e=this.threshold||0);
y(b)?(c=b,b=1E3):b||0===b||(b=1E3);if(c)c(this.search(f,b,null,!0));else{if(!a||"string"!==typeof a)return d;f=this.encode(a);if(!f.length)return d;a=this.f;a=y(a)?a(f):f.split(D);c=a.length;var g=!0;f=[];var h=r();if(1<c)if(this.depth){var k=!0;var l=a[0];h[l]=1}else a.sort(H);var n;if(!k||(n=this.b)[l])for(var t=k?1:0;t<c;t++){var q=a[t];if(q){if(!h[q]){var p=[];let a=!1,b=0;if(l=k?n[l]:this.c){let c;for(let d=0;d<10-e;d++)if(c=l[d][q])p[b++]=c,a=!0}if(a)f[f.length]=1<b?p.concat.apply([],p):p[0];
else{g=!1;break}h[q]=1}l=q}}else g=!1;if(g)a:{e=[];d=f.length;if(1<d){f.sort(I);k=r();n=f[0];l=n.length;for(a=0;a<l;)k["@"+n[a++]]=1;for(h=g=0;++h<d;){t=!1;q=h===d-1;n=f[h];l=n.length;for(a=0;a<l;)if(c=n[a++],p="@"+c,k[p]&&k[p]===h){if(q){if(e[g++]=c,b&&g===b){d=e;break a}}else k[p]=h+1;t=!0}if(!t)break}}else d&&(e=f[0],b&&e.length>b&&(e=e.slice(0,b)));d=e}return d}};e.prototype.clear=function(){this.destroy();return this.init()};e.prototype.destroy=function(){this.filter=this.stemmer=this.c=this.b=
this.a=null;return this};e.prototype.export=function(){return JSON.stringify([this.c,this.b,this.a])};e.prototype.import=function(a){a=JSON.parse(a);this.c=a[0];this.b=a[1];this.a=a[2]};const w={icase:function(a){return a.toLowerCase()}};return e}(!1),this);
