/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const indexData: string[] = [
  'a', 'a aa', 'a aa aaa',
  'b', 'b bb', 'b bb bbb',
  'c', 'c cc', 'c cc ccc',
  'd', 'd dd', 'd dd ddd',
  'e', 'e ee', 'e ee eee',
  'f', 'f ff', 'f ff fff',
  'g', 'g gg', 'g gg ggg',
  'h', 'h hh', 'h hh hhh',
  'i', 'i ii', 'i ii iii',
  'j', 'j jj', 'j jj jjj',
  'k', 'k kk', 'k kk kkk',
  'l', 'l ll', 'l ll lll',
  'm', 'm mm', 'm mm mmm',
  'n', 'n nn', 'n nn nnn',
  'o', 'o oo', 'o oo ooo',
  'p', 'p pp', 'p pp ppp',
  'q', 'q qq', 'q qq qqq'
];

export default indexData
